---
version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  web:
    build: .
    image: transito
    command: python manage.py runserver
    volumes:
        - .:/code
    ports:
        - "8000:8000"
    depends_on:
        - db

volumes:
  db:
    driver: local
  web:
    driver: local