# Generated by Django 4.1.6 on 2023-02-14 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "placa",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("marca", models.CharField(max_length=20)),
                ("modelo", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persona.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Infraccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("lugar", models.CharField(max_length=50)),
                ("comentarios", models.CharField(max_length=200)),
                (
                    "policia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculo.vehiculo",
                    ),
                ),
            ],
        ),
    ]
