# Generated by Django 4.1.6 on 2023-02-13 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("persona", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("marca", models.CharField(max_length=20)),
                ("modelo", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=20)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="persona.persona",
                    ),
                ),
            ],
        ),
    ]
