# Generated by Django 4.1.6 on 2023-02-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("policia", "0001_initial"),
        ("vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehiculo",
            name="id",
        ),
        migrations.AlterField(
            model_name="vehiculo",
            name="placa",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="Infraccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("lugar", models.CharField(max_length=50)),
                ("comentarios", models.CharField(max_length=200)),
                (
                    "policia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policia.policia",
                    ),
                ),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehiculo.vehiculo",
                    ),
                ),
            ],
        ),
    ]
