# Generated by Django 4.1.6 on 2023-02-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehiculo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infraccion",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name="infraccion",
            unique_together={("vehiculo", "timestamp", "lugar", "comentarios")},
        ),
    ]
